---
title: "WineRegression"
author: "Mohammed Ali"
date: "July 29, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

# Read in data

```{r}
wine <- read.csv("data/wine.csv")
glimpse(wine)
summary(wine)
```

# Linear Regression (one variable)


```{r}
model1 = lm(Price ~ AGST, data=wine)
summary(model1)
```

## Sum of Squared Errors
```{r}
model1$residuals
SSE <- sum(model1$residuals^2)
SSE
```


# Linear Regression (two variables)
```{r}
model2 <- lm(Price ~ AGST + HarvestRain, data=wine)
summary(model2)
```


## Sum of Squared Errors
```{r}
SSE <- sum(model2$residuals^2)
SSE
```

# Linear Regression (all variables)
```{r}
model3 <- lm(Price ~ AGST + HarvestRain + WinterRain + Age + FrancePop, data=wine)
summary(model3)
```


## Sum of Squared Errors
```{r}
SSE <- sum(model3$residuals^2)
SSE
```

# Remove FrancePop
```{r}
model4 <- lm(Price ~ AGST + HarvestRain + WinterRain + Age, data=wine)
summary(model4)
```

# Correlations
```{r}
cor(wine$WinterRain, wine$Price)
cor(wine$Age, wine$FrancePop)
cor(wine)
```

## Remove Age and FrancePop
```{r}
model5 <- lm(Price ~ AGST + HarvestRain + WinterRain, data=wine)
summary(model5)
```

# Prediction

## Read in test set
```{r}
wineTest <- read.csv("data/wine_test.csv")
glimpse(wineTest)
```

## Make test set predictions
```{r}
predictTest <- predict(model4, newdata=wineTest)
predictTest
```

## Compute R-squared
```{r}
SSE <- sum((wineTest$Price - predictTest)^2)
SST <- sum((wineTest$Price - mean(wine$Price))^2)
1 - SSE/SST
```

