---
title: "CART in R"
author: "Mohammed Ali"
date: "July 9, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(caTools)
library(rpart)
library(rpart.plot)
library(ROCR)
library(randomForest)
library(caret)
library(e1071)
```

# Data Setup
Read data and split it to train and test datasets
```{r read}
stevens <- read.csv("data/stevens.csv")
glimpse(stevens)
set.seed(3000)
spl <- sample.split(stevens$Reverse, SplitRatio = 0.7)
train <- subset(stevens, spl == TRUE)
test <- subset(stevens, spl == FALSE)
```

# Model building

```{r build_model}
stevensTree <- rpart(data = train, Reverse ~ Circuit + Issue + Petitioner + Respondent + LowerCourt + Unconst, minbucket = 5, method = "class")
prp(stevensTree)
```

# Prediction and Accuarcy Measure
```{r predict}
predictCart <- predict(stevensTree, newdata = test, type="class")
table(test$Reverse, predictCart)
```

# Model Performance
```{r performance}
predictroc <- predict(stevensTree, newdata = test)
pred <- prediction(predictroc[,2], test$Reverse)
perf <- performance(pred, "tpr", "fpr")
plot(perf)
```

# Compute the AUC
```{r auc}
as.numeric(performance(pred, "auc")@y.values)
```

# Random Forest
```{r random_forest}
train$Reverse = as.factor(train$Reverse)
test$Reverse = as.factor(test$Reverse)
stevensForest <- randomForest(Reverse ~ Circuit + Issue + Petitioner + Respondent + LowerCourt + Unconst, data = train, nodesize = 25, ntree = 200)
predictForest <- predict(stevensForest, newdata = test)
table(test$Reverse, predictForest)
```

# Crossvalidation

```{r crossvalidation}
numFolds <- trainControl(method = "cv", number = 10)
cpGrid <- expand.grid(.cp = seq(0.01, 0.5, 0.1))
train(Reverse ~ Circuit + Issue + Petitioner + Respondent + LowerCourt + Unconst, data = train, method = "rpart",
      trControl = numFolds, tuneGrid = cpGrid)
stevensTreeCV <- rpart(Reverse ~ Circuit + Issue + Petitioner + Respondent + LowerCourt + Unconst, data = train, method = class, cp = 0.11)
predicateCV = predict(stevensTreeCV, newdata = test, type = "class")
table(test$Reverse, predicateCV)

```

